spring:
  jpa:
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
      dialect: com.back.global.jpa.config.CustomTestPostgreSQLDialect
custom:
  notProdMembers: []
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    dbHost: ${custom.dev.dbHost}"
    dbName: "${custom.dev.dbName}"