server:
  port: 8080
  shutdown: graceful
  forward-headers-strategy: native
spring:
  application:
    name: back
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true
  web:
    resources:
      add-mappings: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  session:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5432/${custom.site.dbName}?reWriteBatchedInserts=true
    username: admin
    password: lldj123414
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.back.global.jpa.config.CustomPostgreSQLDialect
        default_batch_fetch_size: 128
        jdbc:
          batch_size: 128
          order_inserts: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    show-sql: true
logging:
  level:
    com.back: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.hibernate.orm.jdbc.batch: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:3000"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
    dbName: slog_dev
  test:
    cookieDomain: ${custom.dev.cookieDomain}
    frontUrl: ${custom.dev.frontUrl}
    backUrl: ${custom.dev.backUrl}
    dbName: slog_test
  prod:
    cookieDomain: slog-2026-02-15.oa.gg
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
    dbName: slog_prod
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    dbName: "${custom.dev.dbName}"
  jwt:
    secretKey: ${CUSTOM__JWT__SECRET_KEY}
  accessToken:
    expirationSeconds: "#{60*20}"
  systemMemberApiKey: ${CUSTOM__JWT__SECRET_KEY}
  cache:
    ttl-seconds: 3600
    ttl-overrides: { }