spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/slog_test?reWriteBatchedInserts=true
    username: admin
    password: lldj123414
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: com.back.global.jpa.config.CustomTestPostgreSQLDialect