spring:
  jpa:
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
      dialect: com.back.global.jpa.config.CustomTestPostgreSQLDialect
custom:
  notProdMembers: []
  site:
    cookieDomain: "${custom.test.cookieDomain}"
    frontUrl: "${custom.test.frontUrl}"
    backUrl: "${custom.test.backUrl}"
    dbHost: "${custom.test.dbHost}"
    dbName: "${custom.test.dbName}"