spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: com.back.global.jpa.config.CustomTestPostgreSQLDialect
custom:
  site:
    cookieDomain: "${custom.test.cookieDomain}"
    frontUrl: "${custom.test.frontUrl}"
    backUrl: "${custom.test.backUrl}"
    dbName: "${custom.test.dbName}"