server:
  port: 8080
  shutdown: graceful
  forward-headers-strategy: native
spring:
  application:
    name: back
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION__KAKAO__CLIENT_ID:}
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          google:
            client-id: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION__GOOGLE__CLIENT_ID:}
            client-secret: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION__GOOGLE__CLIENT_SECRET:}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-name: Google
            scope: profile
            authorization-grant-type: authorization_code
          naver:
            client-id: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION__NAVER__CLIENT_ID:}
            client-secret: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION__NAVER__CLIENT_SECRET:}
            scope: profile_nickname, profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true
  web:
    resources:
      add-mappings: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${custom.site.dbHost}:5432/${custom.site.dbName}?reWriteBatchedInserts=true
    username: postgres
    password: lldj123414
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.back.global.jpa.config.CustomPostgreSQLDialect
        default_batch_fetch_size: 128
        jdbc:
          batch_size: 128
          order_inserts: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    show-sql: true
logging:
  level:
    com.back: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.hibernate.orm.jdbc.batch: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:3000"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
    dbHost: localhost
    dbName: slog_dev
  test:
    cookieDomain: localhost
    frontUrl: "http://${custom.test.cookieDomain}:3000"
    backUrl: "http://${custom.test.cookieDomain}:${server.port}"
    dbHost: localhost
    dbName: slog_test
  prod:
    cookieDomain: slog.gg
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
    dbHost: pg_1
    dbName: slog_prod
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    dbHost: "${custom.dev.dbHost}"
    dbName: "${custom.dev.dbName}"
  jwt:
    secretKey: ${CUSTOM__JWT__SECRET_KEY}
  accessToken:
    expirationSeconds: "#{60*20}"
  notProdMembers: []
  systemMemberApiKey: ${CUSTOM__JWT__SECRET_KEY}
  cache:
    ttl-seconds: 3600
    ttl-overrides: { }
