name: slog_dev
services:
  slog_dev_db:
    image: jangka512/pgj:latest
    container_name: slog_dev_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lldj123414
      POSTGRES_DATABASE: postgres
      POSTGRES_DATABASES: slog_dev,slog_test
      TZ: Asia/Seoul
    command: >
      postgres
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c wal_level=minimal
      -c max_wal_senders=0
      -c random_page_cost=1.1
      -c jit=off
      -c log_min_duration_statement=1000
      -c log_statement=all
      -c tcp_keepalives_idle=60
      -c tcp_keepalives_interval=10
      -c tcp_keepalives_count=6
      -c idle_in_transaction_session_timeout=60000
    volumes:
      - db_data:/var/lib/postgresql
volumes:
  db_data: